spring:
  application:
    name: TripManagementSystem
  datasource:
    url: jdbc:postgresql://localhost:5432/trip_management
    driver-class-name: org.postgresql.Driver
    username: admin
    password: changemeinprod!
  jpa:
    hibernate:
      ddl-auto: update

# Logging configuration
logging:
  level:
    root: INFO # Set the root logging level to INFO
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"